### ISSUE TITLE
Remove the sound

### ISSUE THREAD

**Issue by ChrisCodeT** [codekraft-studio/angular-video-background#2]
Any way to remove the sound of the video?

**Comment by groggy84** [comment]
attribute  add volume=0

**Comment by b4dnewz** [comment]
the answer by @groggy84 is good, all the attributes will be forwarded to the final element, but this make me think about an integration for scope controlled volume.
updates on this coming soon

**Comment by b4dnewz** [comment]
I've noticed right now It was already taken from attributes [here](https://github.com/codekraft-studio/angular-video-background/blob/master/src/angular-video-background.directive.js#L33) but not documented in the readme file, now I fix it.
