### ISSUE TITLE
Demo not working on Chrome

### ISSUE THREAD

**Issue by pulgaroja** [codekraft-studio/angular-video-background#4]
Hi, so not sure if this is just me but when I opened your demo the video does not play, I can see the still image of the lamps but no video playback. I checked on Firefox and Safari and I can see the video play which is why I think it's Chrome related. 

I'm on the latest Chrome version: Version 70.0.3538.67 (Official Build) (64-bit)

**Comment by pulgaroja** [comment]
Seems it requires the use of DomSanitizer from '@angular/platform-browser', but not sure. Anyways hope it helps.

**Comment by b4dnewz** [comment]
> Seems it requires the use of DomSanitizer from '@angular/platform-browser'

it looks like an Angular >= 2 dependency, this package is old and is for Angular1 only, are you sure about the issue?
